project_id = "vjyzhgwiajobfpumeqvy"

[functions.send-auth-email]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.import-providers]
verify_jwt = true

[functions.get-maps-key]
verify_jwt = false

[functions.ai-provider-search]
verify_jwt = false